# Generated by Django 3.2.7 on 2021-09-11 13:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان وب سایت')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='عنوان')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name='شرکت')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن همراه (جهت دریافت اطلاع رسانی پیامکی وبسایت)')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=70, verbose_name='ایمیل')),
                ('icon', models.ImageField(help_text='لوگو اصلی نمایش در بالای سایت', upload_to='images/', verbose_name='لوگو')),
                ('shortcut_icon', models.ImageField(blank=True, help_text='نسبت 1.1 به منظور نمایش در تب مرورگر', upload_to='images/', verbose_name='لوگو کوچک')),
                ('facecbook', models.CharField(blank=True, max_length=50, verbose_name='فیسبوک')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='تلگرام')),
                ('youtube', models.CharField(blank=True, max_length=50, verbose_name='یوتیوب')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='توییتر')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='درباره ما')),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='تماس با ما')),
                ('worktime', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='ساعت کاری')),
                ('customerservices', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='خدمات مشتریان')),
                ('notices', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='اعلامیه وبسایت')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعات وب سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
