# Generated by Django 3.2.7 on 2021-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facecbook',
            field=models.CharField(blank=True, max_length=100, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='توییتر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, verbose_name='یوتیوب'),
        ),
    ]
