# Generated by Django 3.2.7 on 2021-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210911_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
    ]
