# Generated by Django 3.2.7 on 2021-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210917_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutme1',
            field=models.TextField(blank=True, verbose_name='درباره من 1'),
        ),
    ]
