# Generated by Django 3.2.7 on 2021-09-12 14:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='دسته بندی')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='works.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس url محصول(slug)')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر اصلی')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ManyToManyField(to='works.Category', verbose_name='دسته بندی')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
